# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RozpoznawanieTwarzy.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 640))
        self.tabWidget.setMaximumSize(QtCore.QSize(950, 800))
        self.tabWidget.setObjectName("tabWidget")
        self.WelcomeTab = QtWidgets.QWidget()
        self.WelcomeTab.setObjectName("WelcomeTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.WelcomeTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 3, 2, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.WelcomeTab)
        self.textEdit.setEnabled(False)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_6.addWidget(self.textEdit, 3, 1, 1, 1)
        self.WelcomeButton = QtWidgets.QPushButton(self.WelcomeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WelcomeButton.sizePolicy().hasHeightForWidth())
        self.WelcomeButton.setSizePolicy(sizePolicy)
        self.WelcomeButton.setMinimumSize(QtCore.QSize(0, 50))
        self.WelcomeButton.setMaximumSize(QtCore.QSize(1000, 200))
        self.WelcomeButton.setObjectName("WelcomeButton")
        self.gridLayout_6.addWidget(self.WelcomeButton, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.WelcomeTab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem4, 4, 1, 1, 1)
        self.tabWidget.addTab(self.WelcomeTab, "")
        self.TrainTab = QtWidgets.QWidget()
        self.TrainTab.setObjectName("TrainTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TrainTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 8, 1, 1)
        self.Eigenfaces_label = QtWidgets.QLabel(self.TrainTab)
        self.Eigenfaces_label.setMinimumSize(QtCore.QSize(250, 0))
        self.Eigenfaces_label.setMaximumSize(QtCore.QSize(500, 500))
        self.Eigenfaces_label.setText("")
        self.Eigenfaces_label.setObjectName("Eigenfaces_label")
        self.gridLayout_2.addWidget(self.Eigenfaces_label, 2, 3, 1, 1)
        self.Neuralnetworks_label = QtWidgets.QLabel(self.TrainTab)
        self.Neuralnetworks_label.setMinimumSize(QtCore.QSize(250, 0))
        self.Neuralnetworks_label.setMaximumSize(QtCore.QSize(500, 16777215))
        self.Neuralnetworks_label.setText("")
        self.Neuralnetworks_label.setObjectName("Neuralnetworks_label")
        self.gridLayout_2.addWidget(self.Neuralnetworks_label, 2, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 2, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 2, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.LearnEigenfaces = QtWidgets.QPushButton(self.TrainTab)
        self.LearnEigenfaces.setMinimumSize(QtCore.QSize(0, 40))
        self.LearnEigenfaces.setObjectName("LearnEigenfaces")
        self.gridLayout_7.addWidget(self.LearnEigenfaces, 1, 0, 2, 1)
        self.LearnNetworks = QtWidgets.QPushButton(self.TrainTab)
        self.LearnNetworks.setMinimumSize(QtCore.QSize(0, 40))
        self.LearnNetworks.setObjectName("LearnNetworks")
        self.gridLayout_7.addWidget(self.LearnNetworks, 1, 2, 2, 1)
        self.cnn_label_state = QtWidgets.QLabel(self.TrainTab)
        self.cnn_label_state.setObjectName("cnn_label_state")
        self.gridLayout_7.addWidget(self.cnn_label_state, 0, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem9, 0, 1, 3, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 4, 2, 1, 6)
        self.label_2 = QtWidgets.QLabel(self.TrainTab)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 6)
        spacerItem10 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem10, 5, 1, 1, 8)
        spacerItem11 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 2, 7, 1, 1)
        self.tabWidget.addTab(self.TrainTab, "")
        self.VisualizationTab = QtWidgets.QWidget()
        self.VisualizationTab.setObjectName("VisualizationTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.VisualizationTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.VisualizationTab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.VisualizationEigenfacesTab = QtWidgets.QWidget()
        self.VisualizationEigenfacesTab.setObjectName("VisualizationEigenfacesTab")
        self.tabWidget_2.addTab(self.VisualizationEigenfacesTab, "")
        self.VisualizationPCACoeffTab = QtWidgets.QWidget()
        self.VisualizationPCACoeffTab.setObjectName("VisualizationPCACoeffTab")
        self.tabWidget_2.addTab(self.VisualizationPCACoeffTab, "")
        self.Visualization2PCATab = QtWidgets.QWidget()
        self.Visualization2PCATab.setObjectName("Visualization2PCATab")
        self.tabWidget_2.addTab(self.Visualization2PCATab, "")
        self.VisualizationTSNETab = QtWidgets.QWidget()
        self.VisualizationTSNETab.setObjectName("VisualizationTSNETab")
        self.tabWidget_2.addTab(self.VisualizationTSNETab, "")
        self.VisualizationReconstructionTab = QtWidgets.QWidget()
        self.VisualizationReconstructionTab.setObjectName("VisualizationReconstructionTab")
        self.tabWidget_2.addTab(self.VisualizationReconstructionTab, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.VisualizationTab, "")
        self.AddPersonTab = QtWidgets.QWidget()
        self.AddPersonTab.setObjectName("AddPersonTab")
        self.gridLayout = QtWidgets.QGridLayout(self.AddPersonTab)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem12 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 4, 6, 8, 1)
        self.AddPersonButton = QtWidgets.QPushButton(self.AddPersonTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddPersonButton.sizePolicy().hasHeightForWidth())
        self.AddPersonButton.setSizePolicy(sizePolicy)
        self.AddPersonButton.setMinimumSize(QtCore.QSize(640, 0))
        self.AddPersonButton.setMaximumSize(QtCore.QSize(660, 16777215))
        self.AddPersonButton.setObjectName("AddPersonButton")
        self.gridLayout.addWidget(self.AddPersonButton, 5, 2, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem13, 2, 2, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.AddPersonTab)
        self.label_3.setMinimumSize(QtCore.QSize(640, 50))
        self.label_3.setMaximumSize(QtCore.QSize(600, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 2, 1, 2)
        self.AddPersonLabel = QtWidgets.QLabel(self.AddPersonTab)
        self.AddPersonLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.AddPersonLabel.setMaximumSize(QtCore.QSize(1000, 10000))
        self.AddPersonLabel.setText("")
        self.AddPersonLabel.setObjectName("AddPersonLabel")
        self.gridLayout.addWidget(self.AddPersonLabel, 6, 2, 6, 4)
        self.groupBox = QtWidgets.QGroupBox(self.AddPersonTab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_radio_eigen = QtWidgets.QRadioButton(self.groupBox)
        self.add_radio_eigen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_radio_eigen.setAutoFillBackground(False)
        self.add_radio_eigen.setChecked(True)
        self.add_radio_eigen.setObjectName("add_radio_eigen")
        self.verticalLayout.addWidget(self.add_radio_eigen)
        self.add_radio_nn = QtWidgets.QRadioButton(self.groupBox)
        self.add_radio_nn.setObjectName("add_radio_nn")
        self.verticalLayout.addWidget(self.add_radio_nn)
        self.gridLayout.addWidget(self.groupBox, 4, 5, 2, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 4, 4, 2, 1)
        spacerItem15 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 4, 0, 8, 1)
        self.tabWidget.addTab(self.AddPersonTab, "")
        self.IdentificationTab = QtWidgets.QWidget()
        self.IdentificationTab.setObjectName("IdentificationTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.IdentificationTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.IdentificationTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.iden_radio_eigen = QtWidgets.QRadioButton(self.groupBox_2)
        self.iden_radio_eigen.setChecked(True)
        self.iden_radio_eigen.setObjectName("iden_radio_eigen")
        self.verticalLayout_2.addWidget(self.iden_radio_eigen)
        self.iden_radio_nn = QtWidgets.QRadioButton(self.groupBox_2)
        self.iden_radio_nn.setObjectName("iden_radio_nn")
        self.verticalLayout_2.addWidget(self.iden_radio_nn)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 3, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.IdentificationTab)
        self.label_4.setMinimumSize(QtCore.QSize(640, 50))
        self.label_4.setMaximumSize(QtCore.QSize(600, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 1, 1, 1)
        self.IdentifySearchLabel = QtWidgets.QLabel(self.IdentificationTab)
        self.IdentifySearchLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.IdentifySearchLabel.setMaximumSize(QtCore.QSize(16777, 16777215))
        self.IdentifySearchLabel.setText("")
        self.IdentifySearchLabel.setObjectName("IdentifySearchLabel")
        self.gridLayout_5.addWidget(self.IdentifySearchLabel, 3, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem16, 0, 1, 1, 3)
        self.IdentifyButton = QtWidgets.QPushButton(self.IdentificationTab)
        self.IdentifyButton.setMinimumSize(QtCore.QSize(640, 0))
        self.IdentifyButton.setMaximumSize(QtCore.QSize(660, 16777215))
        self.IdentifyButton.setObjectName("IdentifyButton")
        self.gridLayout_5.addWidget(self.IdentifyButton, 2, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem17, 1, 4, 3, 1)
        spacerItem18 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem18, 1, 0, 3, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem19, 1, 2, 2, 1)
        self.tabWidget.addTab(self.IdentificationTab, "")
        self.IdentifyInImageTab = QtWidgets.QWidget()
        self.IdentifyInImageTab.setObjectName("IdentifyInImageTab")
        self.a = QtWidgets.QGridLayout(self.IdentifyInImageTab)
        self.a.setObjectName("a")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.IdentifyPeopleViewButton_covered = QtWidgets.QPushButton(self.IdentifyInImageTab)
        self.IdentifyPeopleViewButton_covered.setEnabled(False)
        self.IdentifyPeopleViewButton_covered.setMinimumSize(QtCore.QSize(200, 0))
        self.IdentifyPeopleViewButton_covered.setMaximumSize(QtCore.QSize(100, 16777215))
        self.IdentifyPeopleViewButton_covered.setObjectName("IdentifyPeopleViewButton_covered")
        self.gridLayout_8.addWidget(self.IdentifyPeopleViewButton_covered, 4, 3, 1, 1)
        self.IdentifyPeopleViewButton_faces = QtWidgets.QPushButton(self.IdentifyInImageTab)
        self.IdentifyPeopleViewButton_faces.setEnabled(False)
        self.IdentifyPeopleViewButton_faces.setMinimumSize(QtCore.QSize(200, 0))
        self.IdentifyPeopleViewButton_faces.setMaximumSize(QtCore.QSize(100, 16777215))
        self.IdentifyPeopleViewButton_faces.setObjectName("IdentifyPeopleViewButton_faces")
        self.gridLayout_8.addWidget(self.IdentifyPeopleViewButton_faces, 2, 3, 1, 1)
        self.LoadImButton = QtWidgets.QPushButton(self.IdentifyInImageTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadImButton.sizePolicy().hasHeightForWidth())
        self.LoadImButton.setSizePolicy(sizePolicy)
        self.LoadImButton.setMinimumSize(QtCore.QSize(200, 0))
        self.LoadImButton.setObjectName("LoadImButton")
        self.gridLayout_8.addWidget(self.LoadImButton, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.IdentifyInImageTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(500, 0))
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 2, 2, 1, 1)
        self.ShowFacesButton = QtWidgets.QPushButton(self.IdentifyInImageTab)
        self.ShowFacesButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShowFacesButton.sizePolicy().hasHeightForWidth())
        self.ShowFacesButton.setSizePolicy(sizePolicy)
        self.ShowFacesButton.setMinimumSize(QtCore.QSize(200, 0))
        self.ShowFacesButton.setObjectName("ShowFacesButton")
        self.gridLayout_8.addWidget(self.ShowFacesButton, 2, 0, 1, 2)
        self.IdentifyPeopleViewButton_original = QtWidgets.QPushButton(self.IdentifyInImageTab)
        self.IdentifyPeopleViewButton_original.setEnabled(False)
        self.IdentifyPeopleViewButton_original.setMinimumSize(QtCore.QSize(200, 0))
        self.IdentifyPeopleViewButton_original.setMaximumSize(QtCore.QSize(100, 16777215))
        self.IdentifyPeopleViewButton_original.setObjectName("IdentifyPeopleViewButton_original")
        self.gridLayout_8.addWidget(self.IdentifyPeopleViewButton_original, 1, 3, 1, 1)
        self.IdentifyPeopleViewButton_identified = QtWidgets.QPushButton(self.IdentifyInImageTab)
        self.IdentifyPeopleViewButton_identified.setEnabled(False)
        self.IdentifyPeopleViewButton_identified.setMinimumSize(QtCore.QSize(200, 0))
        self.IdentifyPeopleViewButton_identified.setMaximumSize(QtCore.QSize(100, 16777215))
        self.IdentifyPeopleViewButton_identified.setObjectName("IdentifyPeopleViewButton_identified")
        self.gridLayout_8.addWidget(self.IdentifyPeopleViewButton_identified, 3, 3, 1, 1)
        self.IdentifyPeopleButton = QtWidgets.QPushButton(self.IdentifyInImageTab)
        self.IdentifyPeopleButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IdentifyPeopleButton.sizePolicy().hasHeightForWidth())
        self.IdentifyPeopleButton.setSizePolicy(sizePolicy)
        self.IdentifyPeopleButton.setMinimumSize(QtCore.QSize(200, 0))
        self.IdentifyPeopleButton.setObjectName("IdentifyPeopleButton")
        self.gridLayout_8.addWidget(self.IdentifyPeopleButton, 3, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.IdentifyInImageTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(500, 0))
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.IdentifyInImageTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(500, 0))
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 3, 2, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.IdentifyInImageTab)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_faces = QtWidgets.QWidget()
        self.page_faces.setObjectName("page_faces")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_faces)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.GroupImageLabel = QtWidgets.QLabel(self.page_faces)
        self.GroupImageLabel.setText("")
        self.GroupImageLabel.setObjectName("GroupImageLabel")
        self.gridLayout_10.addWidget(self.GroupImageLabel, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_faces)
        self.page_found = QtWidgets.QWidget()
        self.page_found.setObjectName("page_found")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_found)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.GroupImageFoundLabel = QtWidgets.QLabel(self.page_found)
        self.GroupImageFoundLabel.setText("")
        self.GroupImageFoundLabel.setObjectName("GroupImageFoundLabel")
        self.gridLayout_9.addWidget(self.GroupImageFoundLabel, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_found)
        self.page_identified = QtWidgets.QWidget()
        self.page_identified.setObjectName("page_identified")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_identified)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.GroupImageIdentifiedLabel = QtWidgets.QLabel(self.page_identified)
        self.GroupImageIdentifiedLabel.setText("")
        self.GroupImageIdentifiedLabel.setObjectName("GroupImageIdentifiedLabel")
        self.gridLayout_11.addWidget(self.GroupImageIdentifiedLabel, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_identified)
        self.page_vocered = QtWidgets.QWidget()
        self.page_vocered.setObjectName("page_vocered")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_vocered)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.GroupImageCoveredLabel = QtWidgets.QLabel(self.page_vocered)
        self.GroupImageCoveredLabel.setText("")
        self.GroupImageCoveredLabel.setObjectName("GroupImageCoveredLabel")
        self.gridLayout_12.addWidget(self.GroupImageCoveredLabel, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_vocered)
        self.gridLayout_8.addWidget(self.stackedWidget, 5, 0, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.IdentifyInImageTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.IdentifyInImageTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 2)
        self.a.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.IdentifyInImageTab, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Rozpoznawanie twarzy umożliwia identyfikację osób na podstawie wykonanego zdjęcia twarzy. System rozpoznawania twarzy posiada zbiór danych nt. zidentyfikowanych osób, dzięki którym może określić czy nowo dodane zdjęcie należy do osoby z danego zbioru (a jeśli tak, to do której), czy też jest ono fotografią kogoś zupełnie nowego. W tej aplikacji zostały zaimplementowane dwie metody rozpoznawania twarzy:</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">1. Jedną z pierwszych metod umożliwiających stosunkowo skuteczne rozpoznawanie twarzy była metoda &quot;twarzy własnych&quot; (ang. Eigenfaces). Użyła ona reprezentacji twarzy jako punkt w przestrzeni wielowymiarowej używając metody PCA, redukując ilość danych potrzebnych do opisania twarzy. Baza danych zostanie stworzona po naciśnięciu </span><span style=\" font-size:14pt; font-style:italic;\">Przetwarzanie danych &gt; Wyznacz twarze własne</span><span style=\" font-size:14pt;\">. </span><span style=\" font-size:14pt; font-style:italic;\">Zidentyfikuj osobę</span><span style=\" font-size:14pt;\"> znajdzie najbardziej podobną twarz z bazy do nowo dodanej. </span><span style=\" font-size:14pt; font-style:italic;\">Dodaj osobę</span><span style=\" font-size:14pt;\"> umożliwi dodanie nowej osoby do bazy danych.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">2. Sieci neuronowe są popularnym narzędziem do rozpoznawania i klasyfikacji wzorców dlatego też są skuteczną techniką w rozpoznawaniu twarzy. Aby móc rozpoznawać twarze należy w pierwszej kolejności dodać osoby z dużą liczbą zdjęć w </span><span style=\" font-size:14pt; font-style:italic;\">Dodaj Osobę</span><span style=\" font-size:14pt;\">, na których sieć będzie się uczyć. Następnie, po skończonym procesie uczenia w </span><span style=\" font-size:14pt; font-style:italic;\">Przetwarzanie danych &gt; Trenuj sieci neuronowe</span><span style=\" font-size:14pt;\">, rozpoznawanie twarzy jest możliwe.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.WelcomeButton.setText(_translate("MainWindow", "Stwórz Bazę"))
        self.label.setText(_translate("MainWindow", "System rozpoznawania twarzy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.WelcomeTab), _translate("MainWindow", "Witaj"))
        self.LearnEigenfaces.setText(_translate("MainWindow", "Wyznacz twarze własne"))
        self.LearnNetworks.setText(_translate("MainWindow", "Trenuj sieć neuronową"))
        self.cnn_label_state.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Wczytaj bazę danych bądź wytrenuj sieć neuronową"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TrainTab), _translate("MainWindow", "Przetwarzanie danych"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationEigenfacesTab), _translate("MainWindow", "Twarze Własne"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationPCACoeffTab), _translate("MainWindow", "Składowe główne"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Visualization2PCATab), _translate("MainWindow", "Dwie składowe główne"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationTSNETab), _translate("MainWindow", "TSNE"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationReconstructionTab), _translate("MainWindow", "Manualna rekonstrukcja twarzy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VisualizationTab), _translate("MainWindow", "Wizualizacja danych - Twarze własne"))
        self.AddPersonButton.setText(_translate("MainWindow", "START"))
        self.label_3.setText(_translate("MainWindow", "   Po wciśnięciu klawisza START rozpocznie się wykrywanie twarzy i robienie zdjęć, które zostaną \n"
"          przetworzone i dodane do bazy wiedzy, dzięki czemu dana osoba będzie mogła zostać     \n"
"                                                       następnie zidentyfikowana."))
        self.groupBox.setTitle(_translate("MainWindow", "Do bazy danych:"))
        self.add_radio_eigen.setText(_translate("MainWindow", "Twarze własne"))
        self.add_radio_nn.setText(_translate("MainWindow", "Sieci neuronowe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AddPersonTab), _translate("MainWindow", "Dodaj osobę"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Do bazy danych:"))
        self.iden_radio_eigen.setText(_translate("MainWindow", "Twarze własne"))
        self.iden_radio_nn.setText(_translate("MainWindow", "Sieci neuronowe"))
        self.label_4.setText(_translate("MainWindow", "      Po wciśnięciu klawisza START nastąpi wykonanie jednego zdjęcia bezpośrednio po\n"
"detekcji twarzy. Następnie zostanie wyświetlona informacja o statusie wykrycia twarzy."))
        self.IdentifyButton.setText(_translate("MainWindow", "START"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IdentificationTab), _translate("MainWindow", "Zidentyfikuj osobę"))
        self.IdentifyPeopleViewButton_covered.setText(_translate("MainWindow", "Nałożone Twarze"))
        self.IdentifyPeopleViewButton_faces.setText(_translate("MainWindow", "Wykryte Twarze"))
        self.LoadImButton.setText(_translate("MainWindow", "Wczytanie Zdjęcia"))
        self.label_7.setText(_translate("MainWindow", "Znajdź twarze z użyciem metody Viola-Jones i zaznacz je"))
        self.ShowFacesButton.setText(_translate("MainWindow", "Znajdowanie Twarzy"))
        self.IdentifyPeopleViewButton_original.setText(_translate("MainWindow", "Oryginalne Zdjęcie"))
        self.IdentifyPeopleViewButton_identified.setText(_translate("MainWindow", "Zidentyfikowane Osoby"))
        self.IdentifyPeopleButton.setText(_translate("MainWindow", "Identyfikacja Osób"))
        self.label_6.setText(_translate("MainWindow", "Wczytaj zdjęcie z pliku"))
        self.label_8.setText(_translate("MainWindow", "Zidentyfikuj osoby na zdjęciu z wykorzystaniem wcześniej przetrenowanej sieci neuronowej"))
        self.label_5.setText(_translate("MainWindow", "WIDOKI"))
        self.label_9.setText(_translate("MainWindow", "FUNKCJE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IdentifyInImageTab), _translate("MainWindow", "Identyfikacja osób z wczytanego zdjęcia"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

