# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'u.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 616)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 50))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.WelcomeTab = QtWidgets.QWidget()
        self.WelcomeTab.setObjectName("WelcomeTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.WelcomeTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.WelcomeTab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.WelcomeButton = QtWidgets.QPushButton(self.WelcomeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WelcomeButton.sizePolicy().hasHeightForWidth())
        self.WelcomeButton.setSizePolicy(sizePolicy)
        self.WelcomeButton.setMinimumSize(QtCore.QSize(0, 50))
        self.WelcomeButton.setMaximumSize(QtCore.QSize(1000, 200))
        self.WelcomeButton.setObjectName("WelcomeButton")
        self.gridLayout_6.addWidget(self.WelcomeButton, 2, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.WelcomeTab)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_6.addWidget(self.textEdit, 1, 0, 1, 1)
        self.tabWidget.addTab(self.WelcomeTab, "")
        self.TrainTab = QtWidgets.QWidget()
        self.TrainTab.setObjectName("TrainTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TrainTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 8, 1, 1)
        self.Eigenfaces_label = QtWidgets.QLabel(self.TrainTab)
        self.Eigenfaces_label.setMinimumSize(QtCore.QSize(250, 0))
        self.Eigenfaces_label.setMaximumSize(QtCore.QSize(500, 500))
        self.Eigenfaces_label.setText("")
        self.Eigenfaces_label.setObjectName("Eigenfaces_label")
        self.gridLayout_2.addWidget(self.Eigenfaces_label, 2, 3, 1, 1)
        self.Neuralnetworks_label = QtWidgets.QLabel(self.TrainTab)
        self.Neuralnetworks_label.setMinimumSize(QtCore.QSize(250, 0))
        self.Neuralnetworks_label.setMaximumSize(QtCore.QSize(500, 16777215))
        self.Neuralnetworks_label.setText("")
        self.Neuralnetworks_label.setObjectName("Neuralnetworks_label")
        self.gridLayout_2.addWidget(self.Neuralnetworks_label, 2, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.LearnEigenfaces = QtWidgets.QPushButton(self.TrainTab)
        self.LearnEigenfaces.setMinimumSize(QtCore.QSize(0, 40))
        self.LearnEigenfaces.setObjectName("LearnEigenfaces")
        self.gridLayout_7.addWidget(self.LearnEigenfaces, 1, 0, 2, 1)
        self.LearnNetworks = QtWidgets.QPushButton(self.TrainTab)
        self.LearnNetworks.setMinimumSize(QtCore.QSize(0, 40))
        self.LearnNetworks.setObjectName("LearnNetworks")
        self.gridLayout_7.addWidget(self.LearnNetworks, 1, 2, 2, 1)
        self.cnn_label_state = QtWidgets.QLabel(self.TrainTab)
        self.cnn_label_state.setObjectName("cnn_label_state")
        self.gridLayout_7.addWidget(self.cnn_label_state, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 1, 3, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 4, 2, 1, 6)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.TrainTab)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem6, 5, 1, 1, 8)
        self.tabWidget.addTab(self.TrainTab, "")
        self.VisualizationTab = QtWidgets.QWidget()
        self.VisualizationTab.setObjectName("VisualizationTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.VisualizationTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.VisualizationTab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.VisualizationEigenfacesTab = QtWidgets.QWidget()
        self.VisualizationEigenfacesTab.setObjectName("VisualizationEigenfacesTab")
        self.tabWidget_2.addTab(self.VisualizationEigenfacesTab, "")
        self.VisualizationPCACoeffTab = QtWidgets.QWidget()
        self.VisualizationPCACoeffTab.setObjectName("VisualizationPCACoeffTab")
        self.tabWidget_2.addTab(self.VisualizationPCACoeffTab, "")
        self.Visualization2PCATab = QtWidgets.QWidget()
        self.Visualization2PCATab.setObjectName("Visualization2PCATab")
        self.tabWidget_2.addTab(self.Visualization2PCATab, "")
        self.VisualizationTSNETab = QtWidgets.QWidget()
        self.VisualizationTSNETab.setObjectName("VisualizationTSNETab")
        self.tabWidget_2.addTab(self.VisualizationTSNETab, "")
        self.VisualizationReconstructionTab = QtWidgets.QWidget()
        self.VisualizationReconstructionTab.setObjectName("VisualizationReconstructionTab")
        self.tabWidget_2.addTab(self.VisualizationReconstructionTab, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.VisualizationTab, "")
        self.AddPersonTab = QtWidgets.QWidget()
        self.AddPersonTab.setObjectName("AddPersonTab")
        self.gridLayout = QtWidgets.QGridLayout(self.AddPersonTab)
        self.gridLayout.setObjectName("gridLayout")
        self.AddPersonLabel = QtWidgets.QLabel(self.AddPersonTab)
        self.AddPersonLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.AddPersonLabel.setMaximumSize(QtCore.QSize(1000, 10000))
        self.AddPersonLabel.setText("")
        self.AddPersonLabel.setObjectName("AddPersonLabel")
        self.gridLayout.addWidget(self.AddPersonLabel, 11, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.AddPersonTab)
        self.label_3.setMinimumSize(QtCore.QSize(650, 50))
        self.label_3.setMaximumSize(QtCore.QSize(800, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 2, 1, 2)
        self.AddPersonButton = QtWidgets.QPushButton(self.AddPersonTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddPersonButton.sizePolicy().hasHeightForWidth())
        self.AddPersonButton.setSizePolicy(sizePolicy)
        self.AddPersonButton.setMaximumSize(QtCore.QSize(800, 16777215))
        self.AddPersonButton.setObjectName("AddPersonButton")
        self.gridLayout.addWidget(self.AddPersonButton, 5, 2, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 2, 2, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(self.AddPersonTab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_radio_eigen = QtWidgets.QRadioButton(self.groupBox)
        self.add_radio_eigen.setChecked(True)
        self.add_radio_eigen.setObjectName("add_radio_eigen")
        self.verticalLayout.addWidget(self.add_radio_eigen)
        self.add_radio_nn = QtWidgets.QRadioButton(self.groupBox)
        self.add_radio_nn.setObjectName("add_radio_nn")
        self.verticalLayout.addWidget(self.add_radio_nn)
        self.gridLayout.addWidget(self.groupBox, 4, 4, 2, 1)
        self.tabWidget.addTab(self.AddPersonTab, "")
        self.IdentificationTab = QtWidgets.QWidget()
        self.IdentificationTab.setObjectName("IdentificationTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.IdentificationTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.IdentificationTab)
        self.label_4.setMinimumSize(QtCore.QSize(650, 50))
        self.label_4.setMaximumSize(QtCore.QSize(600, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.IdentifySearchLabel = QtWidgets.QLabel(self.IdentificationTab)
        self.IdentifySearchLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.IdentifySearchLabel.setMaximumSize(QtCore.QSize(16777, 16777215))
        self.IdentifySearchLabel.setText("")
        self.IdentifySearchLabel.setObjectName("IdentifySearchLabel")
        self.gridLayout_5.addWidget(self.IdentifySearchLabel, 3, 0, 1, 1)
        self.IdentifyButton = QtWidgets.QPushButton(self.IdentificationTab)
        self.IdentifyButton.setMaximumSize(QtCore.QSize(700, 16777215))
        self.IdentifyButton.setObjectName("IdentifyButton")
        self.gridLayout_5.addWidget(self.IdentifyButton, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.IdentificationTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.iden_radio_eigen = QtWidgets.QRadioButton(self.groupBox_2)
        self.iden_radio_eigen.setChecked(True)
        self.iden_radio_eigen.setObjectName("iden_radio_eigen")
        self.verticalLayout_2.addWidget(self.iden_radio_eigen)
        self.iden_radio_nn = QtWidgets.QRadioButton(self.groupBox_2)
        self.iden_radio_nn.setObjectName("iden_radio_nn")
        self.verticalLayout_2.addWidget(self.iden_radio_nn)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 1, 2, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem8, 0, 0, 1, 2)
        self.tabWidget.addTab(self.IdentificationTab, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "System rozpoznawania twarzy v0.4"))
        self.WelcomeButton.setText(_translate("MainWindow", "Stwórz Bazę"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Rozpoznawanie twarzy umożliwia identyfikację osób na podstawie wykonanego zdjęcia twarzy. System rozpoznawania twarzy posiada zbiór danych nt. zidentyfikowanych osób, dzięki którym może określić czy nowo dodane zdjęcie należy do osoby z danego zbioru (a jeśli tak, to do której), czy też jest ono fotografią kogoś zupełnie nowego. W tej aplikacji zostały zaimplementowane dwie metody rozpoznawania twarzy:</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1. Jedną z pierwszych metod umożliwiających stosunkowo skuteczne rozpoznawanie twarzy była metoda &quot;twarzy własnych&quot; (ang. Eigenfaces). Umożliwiła ona reprezentację twarzy jako punkt w przestrzeni wielowymiarowej używając metody PCA, redukując ilość danych potrzebnych do opisania twarzy. Baza danych zostanie stworzona po naciśnięciu &quot;</span><span style=\" font-size:12pt; font-style:italic;\">Stwórz bazę &gt;&gt; Twarze własne</span><span style=\" font-size:12pt;\">&quot;. &quot;</span><span style=\" font-size:12pt; font-style:italic;\">Zidentyfikuj osobę&quot;</span><span style=\" font-size:12pt;\"> znajdzie najbardziej podobną twarz z bazy do nowo dodanej. </span><span style=\" font-size:12pt; font-style:italic;\">&quot;Dodaj osobę&quot;</span><span style=\" font-size:12pt;\"> umożliwi dodanie nowej osoby do bazy danych.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2. Sieci neuronowe są popularnym narzędziem do rozpoznawania i klasyfikacji wzorców dlatego też są skuteczną techniką w rozpoznawaniu twarzy. Aby móc rozpoznawać twarze należy w pierwszej kolejności dodać osoby z dużą liczbą zdjęć, na których sieć będzie się uczyć. Następnie, po skończonym procesie uczenia, rozpoznawanie twarzy jest możliwe.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.WelcomeTab), _translate("MainWindow", "Witaj"))
        self.LearnEigenfaces.setText(_translate("MainWindow", "Twarze własne"))
        self.LearnNetworks.setText(_translate("MainWindow", "Sieci neuronowe"))
        self.cnn_label_state.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Stwórz bazę i reprezentacje twarzy z wykorzystaniem różnych metod"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TrainTab), _translate("MainWindow", "Stwórz bazę"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationEigenfacesTab), _translate("MainWindow", "Twarze Własne"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationPCACoeffTab), _translate("MainWindow", "Komponenty główne"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Visualization2PCATab), _translate("MainWindow", "Dwa komponenty główne"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationTSNETab), _translate("MainWindow", "TSNE"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationReconstructionTab), _translate("MainWindow", "Manualna rekonstrukcja twarzy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VisualizationTab), _translate("MainWindow", "Wizualizacja danych"))
        self.label_3.setText(_translate("MainWindow", "Po wciśnięciu klawisza START rozpocznie się wykrywanie twarzy i robienie zdjęć, które\n"
"    zostaną przetworzone i dodane do bazy wiedzy, dzięki czemu dana osoba będzie\n"
"                                       mogła zostać nastepnie zidentyfikowana."))
        self.AddPersonButton.setText(_translate("MainWindow", "START"))
        self.groupBox.setTitle(_translate("MainWindow", "Do bazy danych:"))
        self.add_radio_eigen.setText(_translate("MainWindow", "Twarze własne"))
        self.add_radio_nn.setText(_translate("MainWindow", "Sieci neuronowe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AddPersonTab), _translate("MainWindow", "Dodaj osobę"))
        self.label_4.setText(_translate("MainWindow", "      Po wciśnięciu klawisza START nastąpi wykonanie jednego zdjęcia bezpośrednio po\n"
"detekcji twarzy. Następnie zostanie wyświetlona informacja o statusie wykrycia twarzy."))
        self.IdentifyButton.setText(_translate("MainWindow", "START"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Do bazy danych:"))
        self.iden_radio_eigen.setText(_translate("MainWindow", "Twarze własne"))
        self.iden_radio_nn.setText(_translate("MainWindow", "Sieci neuronowe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IdentificationTab), _translate("MainWindow", "Zidentyfikuj osobę"))

