# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'u.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 50))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.WelcomeTab = QtWidgets.QWidget()
        self.WelcomeTab.setObjectName("WelcomeTab")
        self.label = QtWidgets.QLabel(self.WelcomeTab)
        self.label.setGeometry(QtCore.QRect(230, 20, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.WelcomeButton = QtWidgets.QPushButton(self.WelcomeTab)
        self.WelcomeButton.setGeometry(QtCore.QRect(310, 300, 151, 51))
        self.WelcomeButton.setObjectName("WelcomeButton")
        self.tabWidget.addTab(self.WelcomeTab, "")
        self.TrainTab = QtWidgets.QWidget()
        self.TrainTab.setObjectName("TrainTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TrainTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.TrainTab)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 400))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.TrainTab)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LearnEigenfaces = QtWidgets.QPushButton(self.TrainTab)
        self.LearnEigenfaces.setObjectName("LearnEigenfaces")
        self.horizontalLayout.addWidget(self.LearnEigenfaces)
        self.LearnNetworks = QtWidgets.QPushButton(self.TrainTab)
        self.LearnNetworks.setObjectName("LearnNetworks")
        self.horizontalLayout.addWidget(self.LearnNetworks)
        self.LearnWavelet = QtWidgets.QPushButton(self.TrainTab)
        self.LearnWavelet.setObjectName("LearnWavelet")
        self.horizontalLayout.addWidget(self.LearnWavelet)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        self.tabWidget.addTab(self.TrainTab, "")
        self.VisualizationTab = QtWidgets.QWidget()
        self.VisualizationTab.setObjectName("VisualizationTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.VisualizationTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.VisualizationTab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.VisualizationEigenfacesTab = QtWidgets.QWidget()
        self.VisualizationEigenfacesTab.setObjectName("VisualizationEigenfacesTab")
        self.tabWidget_2.addTab(self.VisualizationEigenfacesTab, "")
        self.VisualizationPCACoeffTab = QtWidgets.QWidget()
        self.VisualizationPCACoeffTab.setObjectName("VisualizationPCACoeffTab")
        self.tabWidget_2.addTab(self.VisualizationPCACoeffTab, "")
        self.Visualization2PCATab = QtWidgets.QWidget()
        self.Visualization2PCATab.setObjectName("Visualization2PCATab")
        self.tabWidget_2.addTab(self.Visualization2PCATab, "")
        self.VisualizationTSNETab = QtWidgets.QWidget()
        self.VisualizationTSNETab.setObjectName("VisualizationTSNETab")
        self.tabWidget_2.addTab(self.VisualizationTSNETab, "")
        self.VisualizationReconstructionTab = QtWidgets.QWidget()
        self.VisualizationReconstructionTab.setObjectName("VisualizationReconstructionTab")
        self.tabWidget_2.addTab(self.VisualizationReconstructionTab, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.VisualizationTab, "")
        self.AddPersonTab = QtWidgets.QWidget()
        self.AddPersonTab.setObjectName("AddPersonTab")
        self.gridLayout = QtWidgets.QGridLayout(self.AddPersonTab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.AddPersonTab)
        self.label_3.setMinimumSize(QtCore.QSize(100, 50))
        self.label_3.setMaximumSize(QtCore.QSize(800, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.AddPersonLabel = QtWidgets.QLabel(self.AddPersonTab)
        self.AddPersonLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.AddPersonLabel.setMaximumSize(QtCore.QSize(1000, 10000))
        self.AddPersonLabel.setText("")
        self.AddPersonLabel.setObjectName("AddPersonLabel")
        self.gridLayout.addWidget(self.AddPersonLabel, 10, 2, 1, 1)
        self.AddPersonButton = QtWidgets.QPushButton(self.AddPersonTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddPersonButton.sizePolicy().hasHeightForWidth())
        self.AddPersonButton.setSizePolicy(sizePolicy)
        self.AddPersonButton.setMaximumSize(QtCore.QSize(565, 16777215))
        self.AddPersonButton.setObjectName("AddPersonButton")
        self.gridLayout.addWidget(self.AddPersonButton, 5, 2, 1, 1)
        self.tabWidget.addTab(self.AddPersonTab, "")
        self.IdentificationTab = QtWidgets.QWidget()
        self.IdentificationTab.setObjectName("IdentificationTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.IdentificationTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        self.IdentifySearchLabel = QtWidgets.QLabel(self.IdentificationTab)
        self.IdentifySearchLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.IdentifySearchLabel.setMaximumSize(QtCore.QSize(16777, 16777215))
        self.IdentifySearchLabel.setText("")
        self.IdentifySearchLabel.setObjectName("IdentifySearchLabel")
        self.gridLayout_5.addWidget(self.IdentifySearchLabel, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.IdentificationTab)
        self.label_4.setMinimumSize(QtCore.QSize(100, 50))
        self.label_4.setMaximumSize(QtCore.QSize(600, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.IdentifyButton = QtWidgets.QPushButton(self.IdentificationTab)
        self.IdentifyButton.setMaximumSize(QtCore.QSize(565, 16777215))
        self.IdentifyButton.setObjectName("IdentifyButton")
        self.gridLayout_5.addWidget(self.IdentifyButton, 2, 0, 1, 1)
        self.tabWidget.addTab(self.IdentificationTab, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "System rozpoznawania twarzy v0.2"))
        self.WelcomeButton.setText(_translate("MainWindow", "Stwórz Bazę"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.WelcomeTab), _translate("MainWindow", "Witaj"))
        self.label_2.setText(_translate("MainWindow", "Stwórz bazę i reprezentacje twarzy z wykorzystaniem różnych metod"))
        self.LearnEigenfaces.setText(_translate("MainWindow", "Twarze własne"))
        self.LearnNetworks.setText(_translate("MainWindow", "Sieci neuronowe"))
        self.LearnWavelet.setText(_translate("MainWindow", "Transformacja falkowa"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TrainTab), _translate("MainWindow", "Stwórz bazę"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationEigenfacesTab), _translate("MainWindow", "Twarze Własne"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationPCACoeffTab), _translate("MainWindow", "Komponenty główne"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Visualization2PCATab), _translate("MainWindow", "Dwa komponenty główne"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationTSNETab), _translate("MainWindow", "TSNE"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.VisualizationReconstructionTab), _translate("MainWindow", "Manualna rekonstrukcja twarzy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VisualizationTab), _translate("MainWindow", "Wizualizacja danych"))
        self.label_3.setText(_translate("MainWindow", "Po wciśnięciu klawisza START rozpocznie się wykrywanie twarzy i robienie zdjęć, które\n"
"    zostaną przetworzone i dodane do bazy wiedzy, dzięki czemu dana osoba będzie\n"
"                                       mogła zostać nastepnie zidentyfikowana."))
        self.AddPersonButton.setText(_translate("MainWindow", "START"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AddPersonTab), _translate("MainWindow", "Dodaj osobę"))
        self.label_4.setText(_translate("MainWindow", "   Po wciśnięciu klawisza START nastąpi wykonanie jednego zdjęcia bezpośrednio po\n"
"detekcji twarzy. Następnie zostanie wyświetlona informacja o statusie wykrycia twarzy."))
        self.IdentifyButton.setText(_translate("MainWindow", "START"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IdentificationTab), _translate("MainWindow", "Zidentyfikuj osobę"))

